name: instagram
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500     
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700
    - family: GilroyExtraBold
      fonts:
        - asset: assets/fonts/GilroyExtraBold.ttf
          weight: 800    
    - family: GilroyHeavy
      fonts:
        - asset: assets/fonts/GilroyHeavy.ttf
          weight: 900
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/GilroySemiBold.ttf
          weight: 600
    - family: Shabnam
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

